<?php
    $singleData = $block->getSingleData();
?>

<div>
    <h3>Title</h3>
    <p><?php echo $singleData->getTitle(); ?></p>
</div>
<div>
    <h3>Status</h3>
    <p><?php echo $singleData->getAuthor(); ?></p>
</div>
<div>
    <h3>Description</h3>
    <p><?php echo $this->_filterProvider->getPageFilter()->filter($singleData->getContent()); ?></p>
</div>

<div>
    <h3>Date</h3>
    <p><?php echo $singleData->getCreatedAt(); ?></p>
</div>
