<?php
$singleData = $block->getSingleData();
?>
<h2>Edit Data</h2>
<form class="form customform"
      action="<?php echo $block->getBaseUrl().'customform/index/save'; ?>"
      id="magelearn-customform-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      enctype="multipart/form-data"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><a style="padding: 8px; font-weight: bold; background-color: orangered; color: wheat;" href="<?php echo $block->getBaseUrl().'customform/index/list'; ?>">View list </a></span></legend>
        <div class="field id required">
            <label class="label" for="id"><span><?= $block->escapeHtml(__('Id:')) ?></span></label>
            <div class="control">
                <input name="id"
                       id="id"
                       title="<?= $block->escapeHtmlAttr(__('Id')) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}" value="<?php echo $singleData->getId(); ?>" readonly/>
            </div>
        </div>
        <div class="field first_name required">
            <label class="label" for="first_name"><span><?= $block->escapeHtml(__('First name:')) ?></span></label>
            <div class="control">
                <input name="first_name"
                       id="first_name"
                       title="<?= $block->escapeHtmlAttr(__('First Name')) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}" value="<?php echo $singleData->getFirstName(); ?>"/>
            </div>
        </div>
        <div class="field last_name required">
            <label class="label" for="last_name"><span><?= $block->escapeHtml(__('Last name:')) ?></span></label>
            <div class="control">
                <input name="last_name"
                       id="last_name"
                       title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}" value="<?php echo $singleData->getLastName(); ?>"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"
                        value="<?php echo $singleData->getEmail(); ?>"/>
            </div>
        </div>
        <div class="field phone required">
            <label class="label" for="phone"><span><?= $block->escapeHtml(__('Phone:')) ?></span></label>
            <div class="control">
                <input name="phone" id="phone" title="<?= $block->escapeHtmlAttr(__('Phone')) ?>" class="input-text" type="text" data-validate="{required:true, 'validate-number':true}"  value="<?php echo $singleData->getPhone(); ?>">
            </div>
        </div>
        <div class="field message required">
            <label class="label" for="message"><span><?= $block->escapeHtml(__('Message:')) ?></span></label>
            <div class="control">
                <textarea name="message" id="message" title="<?= $block->escapeHtml(__('Message')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?php echo $this->_filterProvider->getPageFilter()->filter($singleData->getMessage()); ?></textarea>
            </div>
        </div>

    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
