<?php
    $singleData = $block->getSingleData();
?>
<div>
    <h3>First Name</h3>
    <p><?php echo $singleData->getFirstName(); ?></p>
</div>
<div>
    <h3>Last Name</h3>
    <p><?php echo $singleData->getLastName(); ?></p>
</div>
<div>
    <h3>Email</h3>
    <p><?php echo $singleData->getEmail(); ?></p>
</div>
<div>
    <h3>Message</h3>
    <p><?php echo $this->_filterProvider->getPageFilter()->filter($singleData->getMessage()); ?></p>
</div>

<div>
    <h3>Phone</h3>
    <p><?php echo $singleData->getPhone(); ?></p>
</div>
<div>
    <h3>Date</h3>
    <p><?php echo $singleData->getCreatedAt(); ?></p>
</div>
